Repository binder-binFinder/binder-back-end, pull requests merged in 2024-10, with the labels that each got.

#115 북마크 전체 보기 기능으로 통일
  src/main/java/net/binder/api/bin/entity/Bin.java
  src/main/java/net/binder/api/bookmark/controller/BookmarkController.java
  src/main/java/net/binder/api/bookmark/repository/BookmarkQueryRepository.java
  src/main/java/net/binder/api/bookmark/repository/BookmarkRepository.java
  src/main/java/net/binder/api/bookmark/service/BookmarkService.java
  src/test/java/net/binder/api/bookmark/service/BookmarkServiceTest.java
Labels: enhancement

#117 욕설 필터링 후처리 추가 및 쓰레기통 등록 요청 목록에 좌표 포함하여 배포
  src/main/java/net/binder/api/admin/dto/BinRegistrationDetail.java
  src/main/java/net/binder/api/comment/service/CommentService.java
  src/main/java/net/binder/api/filtering/dto/OpenAiMessage.java
  src/main/java/net/binder/api/filtering/service/FilteringManager.java
Labels: documentation

#120 관리자 페이지 요청사항 반영(즉시 수정시, 수정 요청 승인시)
  src/main/java/net/binder/api/admin/repository/AdminBinModificationQueryRepository.java
  src/main/java/net/binder/api/admin/repository/AdminBinRegistrationQueryRepository.java
  src/main/java/net/binder/api/admin/service/AdminBinManagementService.java
  src/main/java/net/binder/api/admin/service/AdminBinModificationService.java
  src/main/java/net/binder/api/admin/service/AdminBinRegistrationService.java
  src/main/java/net/binder/api/bin/dto/BinUpdateRequest.java
  src/main/java/net/binder/api/bin/repository/BinQueryRepository.java
  src/main/java/net/binder/api/bin/service/BinManager.java
  src/main/java/net/binder/api/bin/service/BinModificationManager.java
  src/main/java/net/binder/api/bin/service/BinModificationReader.java
  src/main/java/net/binder/api/bin/service/BinReader.java
  src/main/java/net/binder/api/bin/service/BinRegistrationManager.java
  src/main/java/net/binder/api/bin/service/BinRegistrationReader.java
  src/test/java/net/binder/api/admin/service/AdminBinManagementServiceTest.java
  src/test/java/net/binder/api/admin/service/AdminBinModificationServiceTest.java
Labels: enhancement

#122 Feature/searchlog
  src/main/java/net/binder/api/search/service/SearchService.java
  src/main/java/net/binder/api/searchlog/SearchLog.java
  src/main/java/net/binder/api/searchlog/controller/SearchLogController.java
  src/main/java/net/binder/api/searchlog/dto/SearchLogItem.java
  src/main/java/net/binder/api/searchlog/entity/SearchLog.java
  src/main/java/net/binder/api/searchlog/repository/SearchLogQueryRepository.java
  src/main/java/net/binder/api/searchlog/repository/SearchLogRepository.java
  src/main/java/net/binder/api/searchlog/service/SearchLogService.java
  src/test/java/net/binder/api/searchlog/service/SearchLogServiceTest.java
Labels: enhancement

#126 Fix/bookmark
  src/main/java/net/binder/api/bookmark/dto/BookmarkProjection.java
  src/main/java/net/binder/api/bookmark/dto/BookmarkResponse.java
  src/main/java/net/binder/api/bookmark/dto/CreateBookmarkRequest.java
  src/main/java/net/binder/api/bookmark/repository/BookmarkQueryRepository.java
  src/main/java/net/binder/api/bookmark/service/BookmarkService.java
  src/main/java/net/binder/api/search/dto/SearchRequest.java
  src/main/java/net/binder/api/search/repository/SearchQueryRepository.java
  src/main/java/net/binder/api/search/service/SearchService.java
  src/test/java/net/binder/api/bookmark/service/BookmarkServiceTest.java
Labels: bug

#127 북마크 버그 수정 건 배포
  src/main/java/net/binder/api/bookmark/dto/BookmarkProjection.java
  src/main/java/net/binder/api/bookmark/dto/BookmarkResponse.java
  src/main/java/net/binder/api/bookmark/dto/CreateBookmarkRequest.java
  src/main/java/net/binder/api/bookmark/repository/BookmarkQueryRepository.java
  src/main/java/net/binder/api/bookmark/service/BookmarkService.java
  src/main/java/net/binder/api/search/dto/SearchRequest.java
  src/main/java/net/binder/api/search/repository/SearchQueryRepository.java
  src/main/java/net/binder/api/search/service/SearchService.java
  src/test/java/net/binder/api/bookmark/service/BookmarkServiceTest.java
Labels: bug, enhancement

#128 fix: 쓰레기통 수정 버그 핫픽스
  src/main/java/net/binder/api/admin/controller/AdminBinManagementController.java
  src/main/java/net/binder/api/admin/dto/AdminBinUpdateRequest.java
  src/main/java/net/binder/api/admin/service/AdminBinManagementService.java
  src/main/java/net/binder/api/admin/service/AdminBinModificationService.java
  src/main/java/net/binder/api/bin/controller/BinController.java
  src/main/java/net/binder/api/bin/dto/UserBinUpdateRequest.java
  src/main/java/net/binder/api/bin/service/BinManager.java
  src/main/java/net/binder/api/bin/service/BinModificationManager.java
  src/main/java/net/binder/api/bin/service/BinService.java
  src/test/java/net/binder/api/admin/service/AdminBinManagementServiceTest.java
Labels: bug, enhancement

#130 refactor: searchlog를 최신순으로 전달, dto에 생성 시간도 포함
  src/main/java/net/binder/api/searchlog/dto/SearchLogItem.java
  src/main/java/net/binder/api/searchlog/repository/SearchLogQueryRepository.java
  src/test/java/net/binder/api/searchlog/service/SearchLogServiceTest.java
Labels: enhancement

#131 검색 기록 로직 변경 배포
  src/main/java/net/binder/api/searchlog/dto/SearchLogItem.java
  src/main/java/net/binder/api/searchlog/repository/SearchLogQueryRepository.java
  src/test/java/net/binder/api/searchlog/service/SearchLogServiceTest.java
Labels: enhancement

#136 좋아요 싫어요 기능 수정해서 배포
  src/main/java/net/binder/api/likeanddislike/controller/MemberDislikeBinController.java
  src/main/java/net/binder/api/likeanddislike/controller/MemberLikeBinController.java
  src/main/java/net/binder/api/likeanddislike/entity/MemberDislikeBin.java
  src/main/java/net/binder/api/likeanddislike/entity/MemberLikeBin.java
  src/main/java/net/binder/api/likeanddislike/repository/MemberDislikeBinRepository.java
  src/main/java/net/binder/api/likeanddislike/repository/MemberLikeBinRepository.java
  src/main/java/net/binder/api/likeanddislike/service/LikeAndDislikeFacade.java
  src/main/java/net/binder/api/likeanddislike/service/MemberDislikeBinService.java
  src/main/java/net/binder/api/likeanddislike/service/MemberLikeBinService.java
  src/main/java/net/binder/api/search/service/SearchService.java
  src/test/java/net/binder/api/bin/service/BinServiceTest.java
  src/test/java/net/binder/api/likeanddislike/service/LikeAndDislikeFacadeTest.java
  src/test/java/net/binder/api/memberlikebin/service/MemberLikeBinServiceTest.java
Labels: enhancement

#137 욕설 필터링 성능개선
  src/main/java/net/binder/api/comment/service/CommentService.java
  src/main/java/net/binder/api/filtering/dto/CurseCheckResult.java
  src/main/java/net/binder/api/filtering/entity/Curse.java
  src/main/java/net/binder/api/filtering/repository/CurseQueryRepository.java
  src/main/java/net/binder/api/filtering/repository/CurseRepository.java
  src/main/java/net/binder/api/filtering/service/AiCheckManager.java
  src/main/java/net/binder/api/filtering/service/CurseManager.java
  src/main/java/net/binder/api/filtering/service/CurseReader.java
  src/main/java/net/binder/api/filtering/service/FilteringService.java
  src/test/java/net/binder/api/filtering/repository/CurseQueryRepositoryTest.java
  src/test/java/net/binder/api/filtering/service/FilteringManagerTest.java
  src/test/java/net/binder/api/filtering/service/FilteringServiceTest.java
Labels: enhancement

#141 refactor: 쓰레기통 등록 시 위치 좌표가 맞지 않으면 예외처리
  src/main/java/net/binder/api/bin/service/BinService.java
  src/main/java/net/binder/api/bin/util/DistanceCalculator.java
  src/main/java/net/binder/api/common/binsetup/dto/PublicBinData.java
  src/main/java/net/binder/api/common/binsetup/service/BinDataSetupService.java
  src/main/java/net/binder/api/common/kakaomap/service/KakaoMapService.java
  src/test/java/net/binder/api/bin/repository/BinRepositoryTest.java
  src/test/java/net/binder/api/bin/service/BinServiceTest.java
  src/test/java/net/binder/api/common/kakaomap/service/KakaoMapServiceTest.java
  src/test/java/net/binder/api/search/service/SearchServiceTest.java
Labels: enhancement

#143 욕설 필터링 트랜잭션 적용 범위 수정
  src/main/java/net/binder/api/comment/service/CommentManager.java
  src/main/java/net/binder/api/comment/service/CommentService.java
  src/main/java/net/binder/api/filtering/service/FilteringService.java
Labels: enhancement
